### ISSUE TITLE
th08: spell practice text is garbled

### ISSUE THREAD

**Issue by monkey03297** [thpatch/thcrap#185]
![th010](https://user-images.githubusercontent.com/83492685/163819766-126d5191-2a04-48c3-9fa1-9d23aa3762ce.png)

**Comment by brliron** [comment]
I thought I fixed this problem a year ago, but either I missed something, or something else broke since I made that fix.
https://github.com/thpatch/thcrap/issues/142

**Comment by xitieshiz2** [comment]
This issue seems still exist, I've tested in `lang_zh-hans` and `lang_en`, here's what it looks like now:
![a976e9a80d6d597dd7b53d4ba93b993b](https://github.com/thpatch/thcrap/assets/75575551/c92bd923-a105-4c63-934e-61b1a5b8409e)
![5ec76346593aa0074796148a7c5d4e8a](https://github.com/thpatch/thcrap/assets/75575551/9e908424-7920-49aa-945f-3bf1200ad329)
And this is what it supposed to look like in Japanese game:
![659a95c7979fd3526dae940b7c12859e](https://github.com/thpatch/thcrap/assets/75575551/fe142c13-a7e0-4c89-b9a7-90030e100b11)
In `lang_zh-hans`, both the string "使用者  %s　　%s %s"(`th08 Spell Practice Owner/Difficulty Line`) and "取得数/挑戦数[最高点]　%s　全主人公合計"(`th08 Spell Practice Highscore Title`) are garbled.
In `lang_en`, these two strings can show translated content, but still with garbled content looks like "縲".
In both patches, the string that represents Mode of the Spell Card and the string that represents the character that the player chosen, just shows their original content, which I'm pretty sure they're uploaded to the wiki.
![image](https://github.com/thpatch/thcrap/assets/75575551/30f85f0a-8863-48d9-97f3-6ad045d916e3)
![image](https://github.com/thpatch/thcrap/assets/75575551/c11db0f3-5cc6-46c3-b766-0c48588564a3)
